version: '3.7'

networks:
  default:
    name: token_wallet_net

volumes:
  db-volume:


services:

  postgres:
    container_name: token_wallet_postgres
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - db-volume:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    container_name: token_wallet_app
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    expose:
      - "8000"
    command: npm run start
    depends_on:
      - postgres
    restart: on-failure
